# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0017_newsblogconfig_author_no_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='hide_author',
            field=models.BooleanField(default=False, help_text="Don't show the author of the article.", verbose_name='Hide author'),
        ),
    ]
